# Generated by Django 3.1.3 on 2020-12-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(blank=True, max_length=255, null=True)),
                ('bgenre', models.CharField(blank=True, max_length=255, null=True)),
                ('binstrument', models.CharField(blank=True, max_length=255, null=True)),
                ('bnationality', models.CharField(blank=True, max_length=255, null=True)),
                ('bemail', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(blank=True, max_length=255, null=True)),
                ('mgenre', models.CharField(blank=True, max_length=255, null=True)),
                ('minstrument', models.CharField(blank=True, max_length=255, null=True)),
                ('mnationality', models.CharField(blank=True, max_length=255, null=True)),
                ('memail', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
